wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.31
    framework: huggingface
    huggingface_version: 4.8.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.7
    t:
      1:
      - 1
      - 5
      - 11
      2:
      - 1
      - 5
      - 11
      4: 3.7.7
      5: 0.10.31
      6: 4.8.1
      8:
      - 5
batch_size:
  desc: null
  value: 64
clip_grad:
  desc: null
  value: 10
criterion:
  desc: null
  value: bce
data_dir:
  desc: null
  value: /opt/ml/Legal-Document-Summarization/data
device:
  desc: null
  value: cuda
drop_out:
  desc: null
  value: 0.5
fold:
  desc: null
  value: 0
hidden_dim:
  desc: null
  value: 512
kfold:
  desc: null
  value: false
log_steps:
  desc: null
  value: 50
lr:
  desc: null
  value: 0.0001
max_seq_len:
  desc: null
  value: 10
model:
  desc: null
  value: Summarizer
model_dir:
  desc: null
  value: /opt/ml/Legal-Document-Summarization/model
model_name:
  desc: null
  value: beomi/KcELECTRA-base
n_epochs:
  desc: null
  value: 5
n_heads:
  desc: null
  value: 4
n_layers:
  desc: null
  value: 3
num_workers:
  desc: null
  value: 4
optimizer:
  desc: null
  value: adamW
output_dir:
  desc: null
  value: /opt/ml/Legal-Document-Summarization/output
output_name:
  desc: null
  value: model.pt
patience:
  desc: null
  value: 30
run_name:
  desc: null
  value: suz
scheduler:
  desc: null
  value: cosine
seed:
  desc: null
  value: 42
submission_dir:
  desc: null
  value: /opt/ml/Legal-Document-Summarization/submission
submission_name:
  desc: null
  value: sample_submission.json
test_file_name:
  desc: null
  value: test.json
train_file_name:
  desc: null
  value: train.json
